<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Librago</RootNamespace>
    <RuntimeIdentifiers>linux-x64</RuntimeIdentifiers>
    <PlaywrightPlatform Condition="$([MSBuild]::IsOSPlatform('Windows'))">win</PlaywrightPlatform>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="appsettings.Local.json"
             CopyToOutputDirectory="Never"
             CopyToPublishDirectory="Never" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Librago.Tests" />
  </ItemGroup>
</Project>
